theme: jekyll-theme-midnight
# Site Settings
locale                   : "en_US"
title                    : "Seminar on Molecular Dynamics (MD) Simulations: International seminar for molecular dynamic simulations for organic and inorganic systems"