theme: jekyll-theme-midnight
# Site Settings
locale                   : "en_US"
title                    : "International seminar for molecular dynamic simulations for organic and inorganic systems"